const AUTO_RULE_HEADER = '【自动拆分阅卷要求】';
const SCORE_NOTE_KEYWORDS = /(分|任答|每点|每项|每个|须答|必须|最多)/;
const PICK_PATTERN = /(任答|任选|答出其中|答任意)\s*(\d+)\s*点/;
const MUST_PATTERN = /(须答|必须答|均须答|均要答|至少答到)\s*(\d+)\s*点/;
const PER_POINT_PATTERN = /每(?:点|项|个点|个要点|个采分点|条)\s*(\d+(?:\.\d+)?)\s*分/;
const STRONG_GROUP_BOUNDARY_PATTERN = /(^|[\n；。!?！？）)])\s*([^\n；。!?！？:：]{1,16})[：:]/g;

function normalizeMultilineText(value) {
  return String(value ?? '')
    .replace(/\r\n?/g, '\n')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function uniqueStrings(values = []) {
  return Array.from(new Set(values.map((item) => String(item || '').trim()).filter(Boolean)));
}

function formatScoreNumber(value) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return '';
  return Number.isInteger(numeric) ? String(numeric) : String(numeric).replace(/\.0$/, '');
}

function isHalfPointStep(value) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric) || numeric <= 0) return false;
  return Math.abs(numeric * 2 - Math.round(numeric * 2)) < 1e-6;
}

function isAutoGeneratedGradingRule(value) {
  return normalizeMultilineText(value).startsWith(AUTO_RULE_HEADER);
}

function stripSubquestionPrefix(value) {
  return String(value || '')
    .replace(/^(?:（|\()\d+(?:）|\))\s*/, '')
    .trim();
}

function extractSubquestionBlocks(text) {
  const normalized = normalizeMultilineText(text);
  if (!normalized) {
    return [];
  }

  const regex = /(^|[\s；。!?！？）)])((?:（|\()\d+(?:）|\)))/g;
  const matches = [];
  let match;
  while ((match = regex.exec(normalized))) {
    const token = match[2];
    const index = match.index + match[1].length;
    if (!matches.length || matches[matches.length - 1].index !== index) {
      matches.push({ token: token.replace('(', '（').replace(')', '）'), index });
    }
  }

  if (!matches.length) {
    return [{ label: '本题', content: normalized }];
  }

  return matches
    .map((item, index) => {
      const start = item.index + item.token.length;
      const end = index + 1 < matches.length ? matches[index + 1].index : normalized.length;
      return {
        label: item.token,
        content: normalized.slice(start, end).trim(),
      };
    })
    .filter((item) => item.content);
}

function parseBracketScore(value) {
  const text = normalizeMultilineText(value);
  if (!text) return null;

  const matches = Array.from(text.matchAll(/[（(]\s*(\d+(?:\.\d+)?)\s*分\s*[）)]/g));
  if (matches.length) {
    return Number(matches[matches.length - 1][1]);
  }

  const plainMatches = Array.from(text.matchAll(/(\d+(?:\.\d+)?)\s*分/g));
  return plainMatches.length ? Number(plainMatches[plainMatches.length - 1][1]) : null;
}

function normalizeSubquestionOrder(value) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric) || numeric <= 0) return null;
  return Math.trunc(numeric);
}

function extractPromptSubquestionBlocks(text) {
  const normalized = normalizeMultilineText(text);
  if (!normalized) {
    return [];
  }

  const chineseNumberMap = {
    一: 1,
    二: 2,
    三: 3,
    四: 4,
    五: 5,
    六: 6,
    七: 7,
    八: 8,
    九: 9,
    十: 10,
  };
  const patterns = [
    /(^|\n)(\s*)(\([1-9]\d*\)|（[1-9]\d*）)/g,
    /(^|\n)(\s*)([①②③④⑤⑥⑦⑧⑨⑩])/g,
    /(^|\n)(\s*)([一二三四五六七八九十]+[、.．)）])/g,
  ];
  const matches = [];

  patterns.some((pattern) => {
    matches.length = 0;
    let match;
    while ((match = pattern.exec(normalized))) {
      const prefix = `${match[1] || ''}${match[2] || ''}`;
      const token = String(match[3] || '').trim();
      const index = match.index + prefix.length;
      const orderMatch = token.match(/[（(]?([1-9]\d*)[）)]?/);
      const chineseMatch = token.match(/([一二三四五六七八九十]+)/);
      const order = normalizeSubquestionOrder(
        orderMatch
          ? Number(orderMatch[1])
          : chineseMatch
            ? (chineseNumberMap[chineseMatch[1]] || null)
            : null,
      );
      if (!order) {
        continue;
      }
      matches.push({ token, index, order });
    }
    return matches.length >= 2;
  });

  if (!matches.length) {
    return [];
  }

  return matches.map((item, index) => {
    const end = index + 1 < matches.length ? matches[index + 1].index : normalized.length;
    return {
      token: item.token,
      order: item.order,
      content: normalized.slice(item.index, end).trim(),
    };
  });
}

function fillMissingSectionScores(catalog, totalScore) {
  if (!Array.isArray(catalog) || !catalog.length) {
    return [];
  }

  const normalizedTotal = Number.isFinite(Number(totalScore)) ? Number(totalScore) : null;
  if (!(normalizedTotal > 0)) {
    return catalog;
  }

  const sections = catalog.map((item) => ({ ...item }));
  const missing = sections.filter((item) => !(Number(item.fullScore) > 0));
  if (missing.length !== 1) {
    return sections;
  }

  const assigned = sections.reduce((sum, item) => sum + (Number(item.fullScore) > 0 ? Number(item.fullScore) : 0), 0);
  const remaining = Number((normalizedTotal - assigned).toFixed(2));
  if (remaining > 0) {
    missing[0].fullScore = remaining;
  }
  return sections;
}

function extractQuestionSubquestionCatalog(question = {}) {
  const type = String(question?.type || '').toLowerCase();
  if (type !== 'subjective') {
    return [];
  }

  const content = normalizeMultilineText(question?.content);
  const totalScore = Number(question?.score || 0);
  const promptBlocks = extractPromptSubquestionBlocks(content);
  const promptByOrder = new Map(
    promptBlocks.map((block, index) => [normalizeSubquestionOrder(block?.order) || index + 1, block]),
  );
  const structuredSections = Array.isArray(question?.gradingRuleTree?.sections)
    ? question.gradingRuleTree.sections
    : [];

  if (structuredSections.length) {
    return fillMissingSectionScores(
      structuredSections.map((section, index) => {
        const order = index + 1;
        const promptBlock = promptByOrder.get(order);
        return {
          order,
          key: `ordinary-${order}`,
          label: normalizeMultilineText(promptBlock?.token) || normalizeMultilineText(section?.label) || `（${order}）小题`,
          prompt: normalizeMultilineText(promptBlock?.content),
          fullScore: normalizePositiveScore(section?.score, 0),
        };
      }),
      totalScore,
    );
  }

  if (!promptBlocks.length) {
    return [{
      order: 1,
      key: 'ordinary-1',
      label: '本题',
      prompt: content,
      fullScore: totalScore > 0 ? totalScore : null,
    }];
  }

  const catalog = promptBlocks.map((block, index) => {
    const order = normalizeSubquestionOrder(block.order) || index + 1;
    return {
      order,
      key: `ordinary-${order}`,
      label: `（${order}）小题`,
      prompt: block.content,
      fullScore: parseBracketScore(block.content),
    };
  });

  return fillMissingSectionScores(catalog, totalScore);
}

function normalizeGroupBoundaryText(text) {
  return normalizeMultilineText(text)
    .replace(/([）)])(?=[^\n；。!?！？:：]{1,16}[：:])/g, '$1\n')
    .replace(/([；。!?！？])(?=[^\n；。!?！？:：]{1,16}[：:])/g, '$1\n');
}

function isLikelyGroupLabel(value) {
  const label = stripSubquestionPrefix(value);
  if (!label || label.length > 16) return false;
  if (/[，,；。!?！？]/.test(label)) return false;
  if (/^\d+$/.test(label)) return false;
  return true;
}

function extractGroupsFromBlock(block) {
  const content = normalizeGroupBoundaryText(block?.content);
  if (!content) {
    return [];
  }

  const matches = [];
  let match;
  while ((match = STRONG_GROUP_BOUNDARY_PATTERN.exec(content))) {
    const label = stripSubquestionPrefix(match[2]);
    if (!isLikelyGroupLabel(label)) {
      continue;
    }
    matches.push({
      label,
      boundaryStart: match.index + match[1].length,
      contentStart: STRONG_GROUP_BOUNDARY_PATTERN.lastIndex,
    });
  }

  if (!matches.length) {
    return [{
      label: block?.label === '本题' ? '' : String(block?.label || '').trim(),
      content,
    }];
  }

  const groups = matches
    .map((item, index) => {
      const end = index + 1 < matches.length ? matches[index + 1].boundaryStart : content.length;
      return {
        label: item.label,
        content: content.slice(item.contentStart, end).trim(),
      };
    })
    .filter((item) => item.content);

  return groups.length
    ? groups
    : [{
        label: block?.label === '本题' ? '' : String(block?.label || '').trim(),
        content,
      }];
}

function stripScoreNotes(text) {
  return normalizeMultilineText(text).replace(/[（(]([^（）()]*)[）)]/g, (full, inner) => {
    return SCORE_NOTE_KEYWORDS.test(String(inner || '')) ? '' : full;
  });
}

function parseScoreSpec(text, options = {}) {
  const normalized = normalizeMultilineText(text);
  const eachScoreMatch = normalized.match(PER_POINT_PATTERN);
  const pickMatch = normalized.match(PICK_PATTERN);
  const mustMatch = normalized.match(MUST_PATTERN);
  const totalScoreMatches = [];

  for (const match of normalized.matchAll(/(\d+(?:\.\d+)?)\s*分/g)) {
    const before = normalized.slice(Math.max(0, match.index - 4), match.index);
    if (/每(?:点|项|个|条)|扣/.test(before)) {
      continue;
    }
    totalScoreMatches.push(Number(match[1]));
  }

  const spec = {
    totalScore: totalScoreMatches.length ? totalScoreMatches[0] : null,
    eachScore: eachScoreMatch ? Number(eachScoreMatch[1]) : null,
    maxPoints: pickMatch ? Number(pickMatch[2]) : mustMatch ? Number(mustMatch[2]) : null,
    selectionType: pickMatch ? 'pick' : (mustMatch || /须答|必须|均须|均要/.test(normalized)) ? 'must' : '',
  };

  return inferScoreSpec(spec, options.pointCount ?? 0, options);
}

function inferScoreSpec(spec, pointCount, options = {}) {
  let totalScore = Number.isFinite(spec?.totalScore) ? Number(spec.totalScore) : null;
  let eachScore = Number.isFinite(spec?.eachScore) ? Number(spec.eachScore) : null;
  let maxPoints = Number.isFinite(spec?.maxPoints) ? Number(spec.maxPoints) : null;
  let selectionType = String(spec?.selectionType || '').trim();
  const defaultTotalScore = Number.isFinite(options.defaultTotalScore) ? Number(options.defaultTotalScore) : null;

  if (!totalScore && defaultTotalScore && defaultTotalScore > 0) {
    totalScore = defaultTotalScore;
  }

  if (!maxPoints && selectionType === 'must' && pointCount > 0) {
    maxPoints = pointCount;
  }

  if (!eachScore && totalScore && maxPoints) {
    const derivedEach = totalScore / maxPoints;
    if (isHalfPointStep(derivedEach) && derivedEach <= 2) {
      eachScore = derivedEach;
    }
  }

  if (!maxPoints && eachScore && totalScore) {
    const derivedMax = totalScore / eachScore;
    if (Number.isInteger(derivedMax) && derivedMax > 0) {
      maxPoints = derivedMax;
    }
  }

  if (!eachScore && !maxPoints && totalScore && pointCount > 0) {
    const derivedEach = totalScore / pointCount;
    if (isHalfPointStep(derivedEach) && derivedEach <= 2) {
      eachScore = derivedEach;
      maxPoints = pointCount;
    } else if (Number.isInteger(totalScore) && totalScore <= 3 && totalScore <= pointCount) {
      eachScore = 1;
      maxPoints = totalScore;
      if (!selectionType && totalScore < pointCount) {
        selectionType = 'pick';
      }
    }
  }

  if (!selectionType && maxPoints && pointCount > 0 && maxPoints < pointCount) {
    selectionType = 'pick';
  }

  if (!totalScore && eachScore && maxPoints) {
    totalScore = eachScore * maxPoints;
  }

  return {
    totalScore,
    eachScore,
    maxPoints,
    selectionType,
  };
}

function insertPointBreaks(text) {
  return normalizeMultilineText(text)
    .replace(/[①②③④⑤⑥⑦⑧⑨⑩]/g, (marker) => `\n${marker} `)
    .replace(/(?:^|\n)\s*[（(]?([0-9]+|[一二三四五六七八九十])[）\).、．]\s*/g, '\n$1. ')
    .replace(/(?:^|\n)\s*[-*]\s+/g, '\n')
    .replace(/[；;]+/g, '；\n');
}

function cleanPointCandidate(value) {
  return String(value || '')
    .replace(/^[+＋]\s*\d+(?:\.\d+)?\s*/, '')
    .replace(/^[（(]?(?:[0-9]+|[一二三四五六七八九十]+|[A-Za-z])[）\).、．]\s*/, '')
    .replace(/\s+/g, ' ')
    .replace(/[；。]+$/g, '')
    .trim();
}

function parseAliasCandidates(innerText) {
  const normalized = String(innerText || '').trim();
  if (!normalized || SCORE_NOTE_KEYWORDS.test(normalized)) {
    return [];
  }
  if (!/^(或|如|例如|写成|也可|可写|可答|答成|别名|即|表现为|包括)/.test(normalized) && !/[\/／、，,；;]/.test(normalized)) {
    return [];
  }

  const aliasSource = normalized
    .replace(/^(或|如|例如|写成|也可|可写|可答|答成|别名|即|表现为|包括)\s*/, '')
    .replace(/或/g, '、');

  return uniqueStrings(
    aliasSource
      .split(/[、，,\/／；;]/)
      .map((item) => cleanPointCandidate(item))
      .filter((item) => item.length >= 2),
  );
}

function extractAliasesFromPoint(pointText) {
  const aliases = [];
  let cleanText = String(pointText || '').replace(/[（(]([^（）()]*)[）)]/g, (full, inner) => {
    const aliasCandidates = parseAliasCandidates(inner);
    if (!aliasCandidates.length) {
      return full;
    }
    aliases.push(...aliasCandidates);
    return '';
  });

  cleanText = cleanPointCandidate(cleanText);
  return {
    text: cleanText || cleanPointCandidate(pointText),
    aliases: uniqueStrings(aliases),
  };
}

function splitPointCandidates(text, options = {}) {
  const normalized = insertPointBreaks(stripScoreNotes(text));
  let parts = normalized
    .split(/\n+/)
    .flatMap((line) => line.split(/[；;]/))
    .map((item) => cleanPointCandidate(item))
    .filter(Boolean);

  if (parts.length <= 1 && options.maxPoints && options.maxPoints > 1) {
    const bySentence = normalizeMultilineText(stripScoreNotes(text))
      .split(/[。!?！？]/)
      .map((item) => cleanPointCandidate(item))
      .filter(Boolean);
    if (bySentence.length > 1 && bySentence.length <= Math.max(options.maxPoints + 2, 6)) {
      parts = bySentence;
    }
  }

  const points = [];
  const seen = new Set();

  parts.forEach((item) => {
    const point = extractAliasesFromPoint(item);
    if (!point.text || seen.has(point.text)) {
      return;
    }
    seen.add(point.text);
    points.push(point);
  });

  return points;
}

function buildGroupTitle(blockLabel, groupLabel) {
  const normalizedBlockLabel = String(blockLabel || '').trim();
  const normalizedGroupLabel = stripSubquestionPrefix(groupLabel);

  if (normalizedBlockLabel && normalizedBlockLabel !== '本题' && normalizedGroupLabel) {
    if (normalizedGroupLabel === normalizedBlockLabel) {
      return normalizedGroupLabel;
    }
    return /部分$|评价$|方面$/.test(normalizedGroupLabel)
      ? `${normalizedBlockLabel}${normalizedGroupLabel}`
      : `${normalizedBlockLabel}${normalizedGroupLabel}部分`;
  }

  if (normalizedGroupLabel) {
    return normalizedGroupLabel;
  }

  return normalizedBlockLabel || '本题';
}

function buildGroupSummary(scoreSpec, pointCount) {
  const parts = [];
  const shouldShowEachScore = !(
    pointCount === 1 &&
    scoreSpec.totalScore &&
    scoreSpec.eachScore &&
    Math.abs(Number(scoreSpec.totalScore) - Number(scoreSpec.eachScore)) < 1e-6
  );

  if (scoreSpec.totalScore) {
    parts.push(`${formatScoreNumber(scoreSpec.totalScore)}分`);
  }

  if (scoreSpec.selectionType === 'pick' && scoreSpec.maxPoints) {
    parts.push(`任答${scoreSpec.maxPoints}点`);
  } else if (scoreSpec.selectionType === 'must' && scoreSpec.maxPoints && scoreSpec.maxPoints > 1) {
    parts.push(`须答${scoreSpec.maxPoints}点`);
  } else if (scoreSpec.maxPoints && pointCount > 0 && scoreSpec.maxPoints < pointCount) {
    parts.push(`最多计${scoreSpec.maxPoints}点`);
  }

  if (scoreSpec.eachScore && shouldShowEachScore) {
    parts.push(`每点${formatScoreNumber(scoreSpec.eachScore)}分`);
  }

  return parts.length ? `${parts.join('，')}。` : '按采分点给分。';
}

function buildPointLine(point, index, eachScore) {
  const suffix = eachScore ? `（${formatScoreNumber(eachScore)}分）` : '';
  return `${index + 1}. ${point.text}${suffix}`;
}

function createRuleNodeId(prefix) {
  return `${prefix}-${crypto.randomUUID()}`;
}

function normalizePositiveScore(value, fallback = 0) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric) || numeric < 0) {
    return Math.max(0, Number(fallback) || 0);
  }
  return numeric;
}

function normalizePositiveIntegerOrNull(value) {
  const numeric = Number(value);
  if (!Number.isFinite(numeric) || numeric <= 0) return null;
  return Math.trunc(numeric);
}

function normalizeStringList(values = []) {
  return uniqueStrings((Array.isArray(values) ? values : []).map((item) => normalizeMultilineText(item)));
}

function createDefaultStructuredPoint(partial = {}) {
  return {
    id: String(partial?.id || createRuleNodeId('point')),
    label: normalizeMultilineText(partial?.label) || '待填写采分点',
    score: normalizePositiveScore(partial?.score, 2),
    aliases: normalizeStringList(partial?.aliases),
    notes: normalizeStringList(partial?.notes),
    allowSimilar: partial?.allowSimilar !== false,
  };
}

function createDefaultStructuredSubquestion(partial = {}, index = 0) {
  const score = normalizePositiveScore(partial?.score, 0);
  const pickEnabled = Boolean(partial?.pickEnabled);
  return {
    id: String(partial?.id || createRuleNodeId('subquestion')),
    label: normalizeMultilineText(partial?.label) || `子问题${index + 1}`,
    score,
    pickEnabled,
    pickCount: pickEnabled ? normalizePositiveIntegerOrNull(partial?.pickCount) : null,
    points: Array.isArray(partial?.points) && partial.points.length
      ? partial.points.map((point) => createDefaultStructuredPoint(point))
      : [createDefaultStructuredPoint()],
  };
}

function createDefaultStructuredSection(partial = {}, index = 0) {
  const score = normalizePositiveScore(partial?.score, 0);
  const pickEnabled = Boolean(partial?.pickEnabled);
  return {
    id: String(partial?.id || createRuleNodeId('section')),
    label: normalizeMultilineText(partial?.label) || `（${index + 1}）小题`,
    score,
    pickEnabled,
    pickCount: pickEnabled ? normalizePositiveIntegerOrNull(partial?.pickCount) : null,
    subquestions: Array.isArray(partial?.subquestions) && partial.subquestions.length
      ? partial.subquestions.map((subquestion, subIndex) => createDefaultStructuredSubquestion(subquestion, subIndex))
      : [createDefaultStructuredSubquestion({ score }, 0)],
  };
}

function buildStructuredPointScore(scoreSpec, pointCount, groupScore) {
  if (scoreSpec?.eachScore) {
    return Number(scoreSpec.eachScore);
  }

  if (groupScore > 0 && pointCount === 1) {
    return groupScore;
  }

  if (groupScore > 0 && pointCount > 0) {
    const derived = groupScore / pointCount;
    if (isHalfPointStep(derived) && derived <= 2) {
      return derived;
    }
  }

  return 2;
}

function resolveStructuredGroupScores(groups, sectionScore) {
  const normalizedSectionScore = normalizePositiveScore(sectionScore, 0);
  const resolved = groups.map((group) => {
    const pointCount = Math.max(1, Number(group.pointCount || 0));
    const scoreSpec = group.scoreSpec || {};
    const explicitScore =
      Number.isFinite(Number(scoreSpec.totalScore))
        ? Number(scoreSpec.totalScore)
        : (
          Number.isFinite(Number(scoreSpec.eachScore))
          && Number.isFinite(Number(scoreSpec.maxPoints))
        )
          ? Number(scoreSpec.eachScore) * Number(scoreSpec.maxPoints)
          : null;

    return {
      ...group,
      pointCount,
      scoreSpec,
      resolvedScore: explicitScore,
    };
  });

  const unresolved = resolved.filter((group) => !(Number(group.resolvedScore) > 0));
  const assigned = resolved.reduce((sum, group) => sum + (Number(group.resolvedScore) > 0 ? Number(group.resolvedScore) : 0), 0);
  const remaining = Math.max(0, Number((normalizedSectionScore - assigned).toFixed(2)));

  if (unresolved.length === 1 && remaining > 0) {
    unresolved[0].resolvedScore = remaining;
  } else if (unresolved.length > 1 && remaining > 0) {
    const totalPoints = unresolved.reduce((sum, group) => sum + Math.max(1, Number(group.pointCount || 1)), 0);
    let distributed = 0;
    unresolved.forEach((group, index) => {
      if (index === unresolved.length - 1) {
        group.resolvedScore = Math.max(0, Number((remaining - distributed).toFixed(2)));
        return;
      }
      const weight = Math.max(1, Number(group.pointCount || 1)) / Math.max(1, totalPoints);
      const value = Math.max(0, Number((remaining * weight).toFixed(2)));
      distributed += value;
      group.resolvedScore = value;
    });
  }

  return resolved.map((group) => ({
    ...group,
    resolvedScore: normalizePositiveScore(group.resolvedScore, 0),
  }));
}

function buildStructuredSubquestionsFromText({ sectionLabel, sectionScore, text }) {
  const groups = extractGroupsFromBlock({ label: sectionLabel, content: text });
  const parsedGroups = (groups.length ? groups : [{ label: '', content: normalizeMultilineText(text) }])
    .map((group, index) => {
      const roughPoints = splitPointCandidates(group.content);
      const scoreSpec = parseScoreSpec(group.content, {
        pointCount: roughPoints.length,
        defaultTotalScore: groups.length <= 1 ? sectionScore : null,
      });
      const points = roughPoints.length
        ? roughPoints
        : [{ text: cleanPointCandidate(stripScoreNotes(group.content)) || '待填写采分点', aliases: [] }];

      return {
        label: normalizeMultilineText(group.label) || `子问题${index + 1}`,
        scoreSpec,
        pointCount: points.length,
        points,
      };
    });

  return resolveStructuredGroupScores(parsedGroups, sectionScore).map((group, groupIndex) => {
    const groupScore = normalizePositiveScore(group.resolvedScore, 0);
    const pointScore = buildStructuredPointScore(group.scoreSpec, group.points.length, groupScore);
    return createDefaultStructuredSubquestion({
      label: group.label || `子问题${groupIndex + 1}`,
      score: groupScore,
      pickEnabled: group.scoreSpec.selectionType === 'pick',
      pickCount: group.scoreSpec.selectionType === 'pick' ? group.scoreSpec.maxPoints : null,
      points: group.points.map((point) => createDefaultStructuredPoint({
        label: point.text || '待填写采分点',
        score: pointScore,
        aliases: point.aliases || [],
        notes: [],
        allowSimilar: true,
      })),
    }, groupIndex);
  });
}

function buildOrdinaryGradingRuleTree(question = {}) {
  const type = String(question?.type || '').toLowerCase();
  if (type !== 'subjective') {
    return null;
  }

  const sections = extractQuestionSubquestionCatalog(question);
  const standardAnswerBlocks = extractSubquestionBlocks(question?.standardAnswer);
  const sectionCount = sections.length || 1;

  return {
    version: 1,
    sections: (sections.length ? sections : [{
      order: 1,
      label: '本题',
      fullScore: Number(question?.score || 0),
      prompt: normalizeMultilineText(question?.content),
    }]).map((section, index) => {
      const sectionScore = normalizePositiveScore(
        section?.fullScore,
        sectionCount === 1 ? Number(question?.score || 0) : 0,
      );
      const standardBlock = standardAnswerBlocks[index];
      const sourceText =
        normalizeMultilineText(standardBlock?.content)
        || normalizeMultilineText(question?.gradingRule)
        || normalizeMultilineText(section?.prompt)
        || normalizeMultilineText(question?.standardAnswer);

      return createDefaultStructuredSection({
        label: normalizeMultilineText(section?.label) || `（${index + 1}）小题`,
        score: sectionScore,
        subquestions: buildStructuredSubquestionsFromText({
          sectionLabel: normalizeMultilineText(section?.label) || `（${index + 1}）小题`,
          sectionScore,
          text: sourceText,
        }),
      }, index);
    }),
  };
}

function normalizeOrdinaryGradingRuleTree(tree, question = {}) {
  const type = String(question?.type || '').toLowerCase();
  if (type !== 'subjective') {
    return null;
  }

  const rawTree = tree && Array.isArray(tree.sections) && tree.sections.length
    ? tree
    : buildOrdinaryGradingRuleTree(question);

  const fallbackSectionScores = extractQuestionSubquestionCatalog(question);

  return {
    version: 1,
    sections: (Array.isArray(rawTree?.sections) ? rawTree.sections : []).map((section, index) => {
      const fallbackSection = fallbackSectionScores[index];
      const subquestions = Array.isArray(section?.subquestions) && section.subquestions.length
        ? section.subquestions.map((subquestion, subIndex) => {
          const points = Array.isArray(subquestion?.points) && subquestion.points.length
            ? subquestion.points.map((point) => createDefaultStructuredPoint(point))
            : [createDefaultStructuredPoint()];

          return createDefaultStructuredSubquestion({
            ...subquestion,
            points,
          }, subIndex);
        })
        : [createDefaultStructuredSubquestion({}, 0)];

      return createDefaultStructuredSection({
        ...section,
        label: normalizeMultilineText(section?.label) || normalizeMultilineText(fallbackSection?.label) || `（${index + 1}）小题`,
        score: normalizePositiveScore(
          section?.score,
          fallbackSection?.fullScore ?? question?.score ?? 0,
        ),
        subquestions,
      }, index);
    }),
  };
}

function buildStructuredSubquestionSummary(subquestion) {
  const summary = [`${formatScoreNumber(subquestion.score)}分`];
  if (subquestion.pickEnabled && subquestion.pickCount) {
    summary.push(`任答${subquestion.pickCount}点`);
  }
  const uniquePointScores = uniqueStrings((subquestion.points || []).map((point) => formatScoreNumber(point.score)).filter(Boolean));
  if (uniquePointScores.length === 1) {
    summary.push(`每点${uniquePointScores[0]}分`);
  }
  return `${summary.join('，')}。`;
}

function buildStructuredSectionSummary(section) {
  const summary = [`${formatScoreNumber(section.score)}分`];
  if (section.pickEnabled && section.pickCount) {
    summary.push(`任答${section.pickCount}个子问题`);
  }
  return `${summary.join('，')}。`;
}

function buildStructuredGradingRuleText(tree, question = {}) {
  const normalizedTree = normalizeOrdinaryGradingRuleTree(tree, question);
  if (!normalizedTree?.sections?.length) {
    return normalizeMultilineText(question?.gradingRule);
  }

  const lines = [AUTO_RULE_HEADER];
  normalizedTree.sections.forEach((section, sectionIndex) => {
    lines.push(`${normalizeMultilineText(section.label) || `（${sectionIndex + 1}）小题`}：${buildStructuredSectionSummary(section)}`);
    if (section.pickEnabled && section.pickCount) {
      lines.push(`一级计分提示：本小题下最多只计任意 ${section.pickCount} 个有效子问题。`);
    }
    section.subquestions.forEach((subquestion, subIndex) => {
      lines.push(`${normalizeMultilineText(section.label) || `（${sectionIndex + 1}）小题`}${normalizeMultilineText(subquestion.label) || `子问题${subIndex + 1}`}：${buildStructuredSubquestionSummary(subquestion)}`);
      lines.push('采分点：');
      subquestion.points.forEach((point, pointIndex) => {
        lines.push(`${pointIndex + 1}. ${normalizeMultilineText(point.label) || '待填写采分点'}（${formatScoreNumber(point.score)}分）`);
        if (point.aliases.length) {
          lines.push(`命中别名：${point.aliases.join('、')}`);
        }
        if (point.notes.length) {
          point.notes.forEach((note) => {
            lines.push(`说明：${note}`);
          });
        }
        if (point.allowSimilar) {
          lines.push('允许近义表达：是');
        }
      });
      if (subquestion.pickEnabled && subquestion.pickCount) {
        lines.push(`计分提示：最多只计任意 ${subquestion.pickCount} 个有效采分点。`);
      }
      lines.push('');
    });
  });
  lines.push('通用提示：同义表述可酌情给分；同一点重复表述不重复给分。');

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}

function buildAutoSplitGradingRule(question = {}) {
  const type = String(question?.type || '').toLowerCase();
  if (type !== 'subjective') {
    return null;
  }

  const standardAnswer = normalizeMultilineText(question.standardAnswer);
  if (!standardAnswer) {
    return null;
  }

  const existingRule = normalizeMultilineText(question.gradingRule);
  const referenceText = [standardAnswer, isAutoGeneratedGradingRule(existingRule) ? '' : existingRule]
    .filter(Boolean)
    .join('\n');
  const blocks = extractSubquestionBlocks(standardAnswer);
  const groupLines = [];
  let pointCount = 0;
  let hasDetailedSpec = false;

  blocks.forEach((block) => {
    const rawGroups = extractGroupsFromBlock(block);
    const multipleGroups = rawGroups.length > 1;

    rawGroups.forEach((group, groupIndex) => {
      const fallbackTotalScore =
        blocks.length === 1 && rawGroups.length === 1 && Number(question.score) > 0 ? Number(question.score) : null;
      const roughPoints = splitPointCandidates(group.content);
      const localSpec = parseScoreSpec(group.content, {
        pointCount: roughPoints.length,
        defaultTotalScore: fallbackTotalScore,
      });
      const mergedSpec =
        !localSpec.totalScore && !localSpec.eachScore && !localSpec.maxPoints && !localSpec.selectionType && blocks.length === 1 && rawGroups.length === 1
          ? parseScoreSpec(referenceText, {
              pointCount: roughPoints.length,
              defaultTotalScore: fallbackTotalScore,
            })
          : localSpec;
      const points = roughPoints.length ? roughPoints : [{ text: cleanPointCandidate(stripScoreNotes(group.content)), aliases: [] }];

      if (!points[0]?.text) {
        return;
      }

      pointCount += points.length;
      if (mergedSpec.totalScore || mergedSpec.eachScore || mergedSpec.maxPoints || mergedSpec.selectionType) {
        hasDetailedSpec = true;
      }

      groupLines.push(`${buildGroupTitle(block.label, multipleGroups || group.label ? group.label : '')}：${buildGroupSummary(mergedSpec, points.length)}`);
      groupLines.push('采分点：');

      points.forEach((point, index) => {
        groupLines.push(buildPointLine(point, index, mergedSpec.eachScore));
        if (point.aliases.length) {
          groupLines.push(`命中别名：${point.aliases.join('、')}`);
        }
      });

      if (mergedSpec.selectionType === 'pick' && mergedSpec.maxPoints && points.length > mergedSpec.maxPoints) {
        groupLines.push(`计分提示：最多只计前 ${mergedSpec.maxPoints} 个有效采分点。`);
      }

      if (groupIndex !== rawGroups.length - 1 || block !== blocks[blocks.length - 1]) {
        groupLines.push('');
      }
    });
  });

  const cleanedLines = groupLines
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  if (!cleanedLines) {
    return null;
  }

  const text = [
    AUTO_RULE_HEADER,
    cleanedLines,
    '',
    '通用提示：同义表述可酌情给分；同一点重复表述不重复给分。',
  ]
    .join('\n')
    .trim();

  return {
    text,
    isDetailed: hasDetailedSpec || pointCount > 1 || blocks.length > 1,
  };
}

function shouldUseGeneratedRule(question, existingRule, generated) {
  if (!generated?.text) {
    return false;
  }

  const normalizedExistingRule = normalizeMultilineText(existingRule);
  const source = String(question?.source || '').toLowerCase();

  if (!normalizedExistingRule) {
    return true;
  }

  if (source === 'manual') {
    return false;
  }

  if (isAutoGeneratedGradingRule(normalizedExistingRule)) {
    return true;
  }

  return false;
}

const { buildEssayRuleSummary, normalizeEssayRuleTree } = require('./essayRuleTree');

function applyAutoSplitGradingRule(question = {}) {
  if (!question || typeof question !== 'object') {
    return question;
  }

  const type = String(question.type || '').toLowerCase();
  if (type === 'choice' || type === 'essay') {
    const essayRuleTree = type === 'essay' ? normalizeEssayRuleTree(question.essayRuleTree, question) : null;
    return {
      ...question,
      standardAnswer: normalizeMultilineText(question.standardAnswer),
      gradingRule: type === 'choice'
        ? ''
        : (normalizeMultilineText(question.gradingRule) || buildEssayRuleSummary(essayRuleTree, question)),
      gradingRuleTree: null,
      essayRuleTree,
    };
  }

  const normalizedQuestion = {
    ...question,
    standardAnswer: normalizeMultilineText(question.standardAnswer),
    gradingRule: normalizeMultilineText(question.gradingRule),
  };
  const gradingRuleTree = normalizeOrdinaryGradingRuleTree(normalizedQuestion.gradingRuleTree, normalizedQuestion);
  const generated = buildAutoSplitGradingRule(normalizedQuestion);
  const structuredRule = buildStructuredGradingRuleText(gradingRuleTree, normalizedQuestion);

  return {
    ...normalizedQuestion,
    gradingRuleTree,
    gradingRule:
      structuredRule
      || (shouldUseGeneratedRule(normalizedQuestion, normalizedQuestion.gradingRule, generated) ? generated?.text : '')
      || normalizedQuestion.gradingRule,
  };
}

module.exports = {
  AUTO_RULE_HEADER,
  isAutoGeneratedGradingRule,
  buildAutoSplitGradingRule,
  buildOrdinaryGradingRuleTree,
  buildStructuredGradingRuleText,
  extractQuestionSubquestionCatalog,
  normalizeOrdinaryGradingRuleTree,
  applyAutoSplitGradingRule,
};
